INSERT INTO public.preset_suggestions (text_prompt, category, language_code, is_active) VALUES
-- Romantic Encounters
('A moonlit walk on the beach turns into a passionate embrace.', 'Romantic Encounters', 'en', true),
('A surprise proposal leads to a night of celebration and love.', 'Romantic Encounters', 'en', true),
('A couple rediscovers their spark during a weekend retreat.', 'Romantic Encounters', 'en', true),
('A first kiss under the stars sets the stage for a romantic journey.', 'Romantic Encounters', 'en', true),
('A love letter found years later rekindles an old flame.', 'Romantic Encounters', 'en', true),
('A dance at a wedding brings two strangers together.', 'Romantic Encounters', 'en', true),
('A shared umbrella in the rain leads to a cozy night in.', 'Romantic Encounters', 'en', true),
('A picnic in the park becomes a feast of the senses.', 'Romantic Encounters', 'en', true),
('A couple''s massage turns into an intimate exploration.', 'Romantic Encounters', 'en', true),
('A candlelit bath for two washes away inhibitions.', 'Romantic Encounters', 'en', true),
('A serenade outside the window melts the heart.', 'Romantic Encounters', 'en', true),
('A cooking class together stirs up more than just food.', 'Romantic Encounters', 'en', true),
('A horseback ride through the countryside ends in a secluded spot.', 'Romantic Encounters', 'en', true),
('A painting session becomes a masterpiece of desire.', 'Romantic Encounters', 'en', true),
('A book club discussion turns into a private reading session.', 'Romantic Encounters', 'en', true),
('A yoga retreat fosters a deep connection.', 'Romantic Encounters', 'en', true),
('A photography project captures more than just images.', 'Romantic Encounters', 'en', true),
('A gardening day together plants the seeds of love.', 'Romantic Encounters', 'en', true),
('A stargazing night reveals the universe''s beauty and their own.', 'Romantic Encounters', 'en', true),
('A shared dream inspires a reality of passion.', 'Romantic Encounters', 'en', true),

-- Forbidden Love
('A priest and a parishioner struggle with their forbidden attraction.', 'Forbidden Love', 'en', true),
('Two spies from opposing sides fall in love.', 'Forbidden Love', 'en', true),
('A royal and a commoner defy societal norms.', 'Forbidden Love', 'en', true),
('Siblings-in-law find themselves drawn to each other.', 'Forbidden Love', 'en', true),
('A therapist and a client cross professional boundaries.', 'Forbidden Love', 'en', true),
('A vampire and a werewolf break the rules of their kinds.', 'Forbidden Love', 'en', true),
('A time traveler falls for someone from the past.', 'Forbidden Love', 'en', true),
('A ghost and a living person share an impossible romance.', 'Forbidden Love', 'en', true),
('A superhero and a villain can''t resist their chemistry.', 'Forbidden Love', 'en', true),
('A mermaid and a sailor navigate their differences.', 'Forbidden Love', 'en', true),
('A witch and a witch hunter find common ground.', 'Forbidden Love', 'en', true),
('A demon and an angel discover love in the midst of war.', 'Forbidden Love', 'en', true),
('A prisoner and a guard develop feelings against all odds.', 'Forbidden Love', 'en', true),
('A celebrity and a fan blur the lines of fame.', 'Forbidden Love', 'en', true),
('A politician and a journalist risk everything for love.', 'Forbidden Love', 'en', true),
('A married couple''s open relationship leads to unexpected connections.', 'Forbidden Love', 'en', true),
('A cult leader and a follower explore their power dynamic.', 'Forbidden Love', 'en', true),
('A shapeshifter and a human learn to trust each other.', 'Forbidden Love', 'en', true),
('A cyborg and an organic human bridge the gap between machine and flesh.', 'Forbidden Love', 'en', true),
('A dragon and a knight forge a bond beyond battle.', 'Forbidden Love', 'en', true),

-- Fantasy and Sci-Fi
('In a world where dreams are shared, two lovers meet every night.', 'Fantasy and Sci-Fi', 'en', true),
('A space explorer discovers a planet where pleasure is the currency.', 'Fantasy and Sci-Fi', 'en', true),
('A wizard''s apprentice accidentally casts a love spell.', 'Fantasy and Sci-Fi', 'en', true),
('A time loop traps two people in a repeating day of passion.', 'Fantasy and Sci-Fi', 'en', true),
('A virtual reality game becomes indistinguishable from reality.', 'Fantasy and Sci-Fi', 'en', true),
('A potion maker brews an elixir that heightens desire.', 'Fantasy and Sci-Fi', 'en', true),
('A shapeshifter uses their abilities to fulfill fantasies.', 'Fantasy and Sci-Fi', 'en', true),
('A telepathic connection leads to an intimate understanding.', 'Fantasy and Sci-Fi', 'en', true),
('A cursed artifact brings two adventurers together.', 'Fantasy and Sci-Fi', 'en', true),
('A portal to another dimension reveals a world of sensual delights.', 'Fantasy and Sci-Fi', 'en', true),
('A mythical creature seduces a mortal.', 'Fantasy and Sci-Fi', 'en', true),
('A futuristic society where arranged marriages are based on compatibility algorithms.', 'Fantasy and Sci-Fi', 'en', true),
('A rebellion against a dystopian regime sparks a romance.', 'Fantasy and Sci-Fi', 'en', true),
('A magical academy where students learn more than just spells.', 'Fantasy and Sci-Fi', 'en', true),
('A quest for a legendary artifact becomes a journey of love.', 'Fantasy and Sci-Fi', 'en', true),
('A parallel universe where one''s alternate self is their lover.', 'Fantasy and Sci-Fi', 'en', true),
('A cybernetic enhancement designed for pleasure.', 'Fantasy and Sci-Fi', 'en', true),
('A alien abduction turns into a consensual encounter.', 'Fantasy and Sci-Fi', 'en', true),
('A medieval fantasy where courtly love is taken to new heights.', 'Fantasy and Sci-Fi', 'en', true),
('A steampunk world where inventors create devices for pleasure.', 'Fantasy and Sci-Fi', 'en', true),

-- BDSM and Power Dynamics
('A novice submissive attends their first play party.', 'BDSM and Power Dynamics', 'en', true),
('A dominant teaches a new partner the art of control.', 'BDSM and Power Dynamics', 'en', true),
('A couple negotiates their first scene together.', 'BDSM and Power Dynamics', 'en', true),
('A public display of affection turns into a private session.', 'BDSM and Power Dynamics', 'en', true),
('A online relationship moves to real life with agreed-upon rules.', 'BDSM and Power Dynamics', 'en', true),
('A professional dominatrix meets a client who changes everything.', 'BDSM and Power Dynamics', 'en', true),
('A switch couple takes turns in control.', 'BDSM and Power Dynamics', 'en', true),
('A bondage workshop leads to a hands-on demonstration.', 'BDSM and Power Dynamics', 'en', true),
('A sensory deprivation experience heightens every touch.', 'BDSM and Power Dynamics', 'en', true),
('A role reversal night flips the script on their dynamic.', 'BDSM and Power Dynamics', 'en', true),
('A contract is signed, sealing their commitment to each other.', 'BDSM and Power Dynamics', 'en', true),
('A punishment turns into a reward.', 'BDSM and Power Dynamics', 'en', true),
('A safe word is tested, strengthening trust.', 'BDSM and Power Dynamics', 'en', true),
('A public outing with discreet toys adds excitement.', 'BDSM and Power Dynamics', 'en', true),
('A weekend retreat dedicated to exploring limits.', 'BDSM and Power Dynamics', 'en', true),
('A mentor guides a newcomer through their first experience.', 'BDSM and Power Dynamics', 'en preparation true),
('A scene inspired by a favorite book or movie.', 'BDSM and Power Dynamics', 'en', true),
('A power exchange during a business trip.', 'BDSM and Power Dynamics', 'en', true),
('A couple incorporates new toys into their play.', 'BDSM and Power Dynamics', 'en', true),
('A dominant surprises their submissive with a special gift.', 'BDSM and Power Dynamics', 'en', true),

-- Historical Settings
('In the roaring ''20s, flappers and gangsters find love.', 'Historical Settings', 'en', true),
('During the Renaissance, artists and muses inspire each other.', 'Historical Settings', 'en', true),
('In ancient Egypt, pharaohs and priestesses share secrets.', 'Historical Settings', 'en', true),
('Victorian-era lovers correspond through coded letters.', 'Historical Settings', 'en', true),
('Samurai and zamanda geishas navigate honor and desire.', 'Historical Settings', 'en', true),
('Pirates and stowaways find romance on the high seas.', 'Historical Settings', 'en', true),
('In the Wild West, outlaws and saloon girls make their own rules.', 'Historical Settings', 'en', true),
('During the French Revolution, passion amidst chaos.', 'Historical Settings', 'en', true),
('In medieval times, knights and ladies engage in courtly love.', 'Historical Settings', 'en', true),
('Ancient Greek philosophers debate love and lust.', 'Historical Settings', 'en', true),
('In the Byzantine Empire, intrigue and seduction in the palace.', 'Historical Settings', 'en', true),
('During the Industrial Revolution, factory workers find solace.', 'Historical Settings', 'en', true),
('In pre-Columbian America, tribal rituals include sensual ceremonies.', 'Historical Settings', 'en', true),
('In feudal Japan, a ronin and a noblewoman defy conventions.', 'Historical Settings', 'en', true),
('During the Age of Exploration, sailors and island natives meet.', 'Historical Settings', 'en', true),
('In ancient Rome, gladiators and patricians cross class lines.', 'Historical Settings', 'en', true),
('In the Viking age, warriors and shieldmaidens bond.', 'Historical Settings', 'en', true),
('During the Enlightenment, free thinkers explore libertine ideas.', 'Historical Settings', 'en', true),
('In the Ottoman Empire, harem dynamics lead to forbidden love.', 'Historical Settings', 'en', true),
('In colonial times, settlers and indigenous people connect.', 'Historical Settings', 'en', true),

-- Workplace Romance
('Late nights at the office lead to more than just work.', 'Workplace Romance', 'en', true),
('A business trip becomes a romantic getaway.', 'Workplace Romance', 'en', true),
('A promotion celebration turns intimate.', 'Workplace Romance', 'en', true),
('A team-building retreat fosters closer bonds.', 'Workplace Romance', 'en', true),
('A workplace rivalry turns into mutual attraction.', 'Workplace Romance', 'en', true),
('A secret admirer leaves notes on the desk.', 'Workplace Romance', 'en', true),
('A coffee break becomes a daily date.', 'Workplace Romance', 'en', true),
('A shared project leads to shared feelings.', 'Workplace Romance', 'en', true),
('A company party ends with a private after-party.', 'Workplace Romance', 'en', true),
('A mentorship program pairs compatible partners.', 'Workplace Romance', 'en', true),
('A lunch meeting extends into the evening.', 'Workplace Romance', 'en', true),
('A job interview takes an unexpected turn.', 'Workplace Romance', 'en', true),
('A training session includes hands-on learning.', 'Workplace Romance', 'en', true),
('A corporate merger brings two executives together.', 'Workplace Romance', 'en', true),
('A workplace accident leads to tender care.', 'Workplace Romance', 'en', true),
('A shared cab ride home becomes a regular occurrence.', 'Workplace Romance', 'en', true),
('A business negotiation turns into a personal deal.', 'Workplace Romance', 'en', true),
('A company outing to a spa relaxes inhibitions.', 'Workplace Romance', 'en', true),
('A tech support call leads to a personal connection.', 'Workplace Romance', 'en', true),
('A workplace competition ends with a tie-breaker in private.', 'Workplace Romance', 'en', true),

-- Vacation and Travel
('A beach resort fling under the sun.', 'Vacation and Travel', 'en', true),
('A mountain cabin provides seclusion for romance.', 'Vacation and Travel', 'en', true),
('A cruise ship romance with a stranger.', 'Vacation and Travel', 'en', true),
('A backpacking trip through Europe leads to love.', 'Vacation and Travel', 'en', true),
('A safari adventure includes a wild night.', 'Vacation and Travel', 'en', true),
('A ski lodge becomes a winter wonderland for two.', 'Vacation and Travel', 'en', true),
('A road trip across the country with a companion.', 'Vacation and Travel', 'en', true),
('A tropical island escape from reality.', 'Vacation and Travel', 'en', true),
('A cultural tour of Asia reveals new desires.', 'Vacation and Travel', 'en', true),
('A camping trip under the stars.', 'Vacation and Travel', 'en', true),
('A luxury hotel stay with all amenities.', 'Vacation and Travel', 'en', true),
('A volunteer trip turns into a meaningful connection.', 'Vacation and Travel', 'en', true),
('A music festival where the vibe is electric.', 'Vacation and Travel', 'en', true),
('A wine tasting tour in the countryside.', 'Vacation and Travel', 'en', true),
('A historical tour where the past comes alive.', 'Vacation and Travel', 'en', true),
('A culinary journey through Italy.', 'Vacation and Travel', 'en', true),
('A wellness retreat for body and soul.', 'Vacation and Travel', 'en', true),
('A photography expedition captures beauty.', 'Vacation and Travel', 'en', true),
('A sailing trip on the open sea.', 'Vacation and Travel', 'en', true),
('A desert oasis offers a mirage of passion.', 'Vacation and Travel', 'en', true),

-- Mystery and Suspense
('A private investigator falls for their client.', 'Mystery and Suspense', 'en', true),
('A witness protection program hides more than identities.', 'Mystery and Suspense', 'en', true),
('A treasure hunt uncovers hidden desires.', 'Mystery and Suspense', 'en', true),
('A masquerade ball conceals true intentions.', 'Mystery and Suspense', 'en', true),
('A haunted house holds secrets of past lovers.', 'Mystery and Suspense', 'en', true),
('A spy uses seduction as a weapon.', 'Mystery and Suspense', 'en', true),
('A journalist investigates a scandal and finds love.', 'Mystery and Suspense', 'en', true),
('A criminal and a cop play a dangerous game.', 'Mystery and Suspense', 'en', true),
('A mysterious inheritance leads to a romantic entanglement.', 'Mystery and Suspense', 'en', true),
('A secret society with erotic initiation rites.', 'Mystery and Suspense', 'en', true),
('A blackmail plot turns into a consensual arrangement.', 'Mystery and Suspense', 'en', true),
('A kidnapping scenario with a twist.', 'Mystery and Suspense', 'en', true),
('A heist where the real prize is each other.', 'Mystery and Suspense', 'en', true),
('A cold case reopened, heating up old flames.', 'Mystery and Suspense', 'en', true),
('A survival situation brings two people closer.', 'Mystery and Suspense', 'en', true),
('A political thriller with bedroom politics.', 'Mystery and Suspense', 'en', true),
('A supernatural mystery with ghostly encounters.', 'Mystery and Suspense', 'en', true),
('A psychological thriller where minds and bodies connect.', 'Mystery and Suspense', 'en', true),
('A noir detective story with a femme fatale.', 'Mystery and Suspense', 'en', true),
('A conspiracy theory that proves true in love.', 'Mystery and Suspense', 'en', true),

-- Humor and Light-hearted
('A mistaken identity leads to a comedy of errors and eros.', 'Humor and Light-hearted', 'en', true),
('A bet between friends to see who can be more seductive.', 'Humor and Light-hearted', 'en', true),
('A cooking disaster turns into a food fight and more.', 'Humor and Light-hearted', 'en', true),
('A pet''s antics bring two owners together.', 'Humor and Light-hearted', 'en', true),
('A karaoke night where singing isn''t the only performance.', 'Humor and Light-hearted', 'en', true),
('A costume party where roles are played to the fullest.', 'Humor and Light-hearted', 'en', true),
('A game of truth or dare gets daring.', 'Humor and Light-hearted', 'en', true),
('A DIY project requires close collaboration.', 'Humor and Light-hearted', 'en', true),
('A lost bet results in a sexy forfeit.', 'Humor and Light-hearted', 'en', true),
('A mix-up at a hotel puts two strangers in the same room.', 'Humor and Light-hearted', 'en', true),
('A comedy club date ends with private jokes.', 'Humor and Light-hearted', 'en', true),
('A playful pillow fight escalates.', 'Humor and Light-hearted', 'en', true),
('A themed party with adult games.', 'Humor and Light-hearted', 'en', true),
('A scavenger hunt with erotic clues.', 'Humor and Light-hearted', 'en', true),
('A dare to try something new in bed.', 'Humor and Light-hearted', 'en', true),
('A humorous misunderstanding clears up with a kiss.', 'Humor and Light-hearted', 'en', true),
('A couple tries to be quiet but fails delightfully.', 'Humor and Light-hearted', 'en', true),
('A playful rivalry in sports turns flirtatious.', 'Humor and Light-hearted', 'en', true),
('A board game night with stripping rules.', 'Humor and Light-hearted', 'en', true),
('A comedy roast where the heat is on.', 'Humor and Light-hearted', 'en', true),

-- Exploration and Discovery
('A couple attends a tantric workshop.', 'Exploration and Discovery', 'en', true),
('A character explores their bisexuality.', 'Exploration and Discovery', 'en', true),
('A first experience with a same-sex partner.', 'Exploration and Discovery', 'en', true),
('A journey into polyamory.', 'Exploration and Discovery', 'en', true),
('A character discovers a new kink.', 'Exploration and Discovery', 'en', true),
('A couple experiments with role-playing.', 'Exploration and Discovery', 'en', true),
('A solo traveler meets a local guide.', 'Exploration and Discovery', 'en', true),
('A character learns the art of erotic massage.', 'Exploration and Discovery', 'en', true),
('A couple tries sensory play.', 'Exploration and Discovery', 'en', true),
('A character explores their dominant side.', 'Exploration and Discovery', 'en', true),
('A submissive learns to voice their desires.', 'Exploration and Discovery', 'en', true),
('A couple incorporates toys into their lovemaking.', 'Exploration and Discovery', 'en', true),
('A character attends a sex-positive event.', 'Exploration and Discovery', 'en', true),
('A couple watches erotic films together.', 'Exploration and Discovery', 'en', true),
('A character writes their own erotic story.', 'Exploration and Discovery', 'en', true),
('A couple takes a class on intimacy.', 'Exploration and Discovery', 'en', true),
('A character practices self-love and acceptance.', 'Exploration and Discovery', 'en', true),
('A couple explores outdoor intimacy.', 'Exploration and Discovery', 'en', true),
('A character discovers the joy of giving pleasure.', 'Exploration and Discovery', 'en', true),
('A couple redefines their relationship boundaries.', 'Exploration and Discovery', 'en', true);