CREATE TABLE public.characters (
  id uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  hobbies text[] NOT NULL,
  description text NOT NULL,
  profession text NOT NULL,
  character_type text NOT NULL,
  personality text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT characters_pkey PRIMARY KEY (id),
  CONSTRAINT characters_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

CREATE TABLE public.stories (
  id uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  audio_url text NULL,
  moral text NULL,
  genre text NULL,
  duration text NOT NULL,
  character_id uuid NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  additional_details text NULL,
  CONSTRAINT stories_pkey PRIMARY KEY (id),
  CONSTRAINT stories_character_id_fkey FOREIGN KEY (character_id) REFERENCES characters(id),
  CONSTRAINT stories_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

CREATE TABLE public.story_chapters (
  id uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
  story_id uuid NOT NULL,
  chapter_number integer NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  generation_method text NULL,
  custom_input text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT story_chapters_pkey PRIMARY KEY (id),
  CONSTRAINT story_chapters_story_id_fkey FOREIGN KEY (story_id) REFERENCES stories(id)
);

CREATE TABLE public.audio_files (
  id uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
  user_id uuid NOT NULL,
  story_id uuid NULL,
  chapter_id uuid NULL,
  voice_id text NOT NULL,
  url text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audio_files_pkey PRIMARY KEY (id),
  CONSTRAINT audio_files_chapter_id_fkey FOREIGN KEY (chapter_id) REFERENCES story_chapters(id),
  CONSTRAINT audio_files_story_id_fkey FOREIGN KEY (story_id) REFERENCES stories(id),
  CONSTRAINT audio_files_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

CREATE TABLE public.challenges (
  id uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
  story_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT challenges_pkey PRIMARY KEY (id),
  CONSTRAINT challenges_story_id_fkey FOREIGN KEY (story_id) REFERENCES stories(id)
);

CREATE TABLE public.challenge_questions (
  id uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
  challenge_id uuid NOT NULL,
  question text NOT NULL,
  options text[] NOT NULL,
  correct_option_index integer NOT NULL,
  explanation text NOT NULL,
  category text NOT NULL,
  target_language text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT challenge_questions_pkey PRIMARY KEY (id),
  CONSTRAINT challenge_questions_challenge_id_fkey FOREIGN KEY (challenge_id) REFERENCES challenges(id)
);

CREATE TABLE public.preset_suggestions (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text_prompt text NOT NULL,
  category text NULL,
  language_code character varying(5) NOT NULL DEFAULT 'es'::character varying,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT preset_suggestions_pkey PRIMARY KEY (id)
);

CREATE TABLE public.profiles (
  id uuid NOT NULL,
  language text NOT NULL,
  child_age integer NULL,
  special_need text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  stripe_customer_id text NULL,
  subscription_status text NULL,
  voice_credits integer NOT NULL DEFAULT 0,
  current_period_end timestamp with time zone NULL,
  monthly_stories_generated integer NOT NULL DEFAULT 0,
  subscription_id text NULL,
  plan_id text NULL,
  period_start_date timestamp with time zone NULL,
  monthly_voice_generations_used integer NULL DEFAULT 0,
  has_completed_setup boolean NOT NULL DEFAULT false,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_stripe_customer_id_key UNIQUE (stripe_customer_id),
  CONSTRAINT profiles_subscription_id_key UNIQUE (subscription_id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);

CREATE TABLE public.user_voices (
  id uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
  user_id uuid NOT NULL,
  voice_id text NOT NULL,
  is_current boolean NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_voices_pkey PRIMARY KEY (id),
  CONSTRAINT user_voices_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);